### PR TITLE
Don't store counters in cache forever

### PR DESCRIPTION
**Pull request by jshore1296**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/statstash/9)

### CODE REVIEW

**Review by sgp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/statstash/9)* status: all files reviewed, 2 unresolved discussions (waiting on @jshore1296)

___
*[statstash.go, line 137 at r1](https://reviewable.io/reviews/pendo-io/statstash/9#-M10y_NuANBdoDPxqNbc:-M10y_Nv4UgEY365Iod8:b-2kthgl) ([raw file](https://github.com/pendo-io/statstash/blob/35f21f06a48e65ceec04b0825c49998f0fcfc149/statstash.go#L137)):*
> ```Go
> 
> 	if _, err = s.cache.IncrementExisting(bucketKey, delta); err != nil {
> 		s.log.Warningf("Failed to increment %s delta %d", bucketKey, delta)
> ```

This can't be a warning level log now as it's now _expected_ behavior whenever making a new key every bucket period. If you can disambiguate a cache miss error from a "bad" error", you might want to do so (because if memstore is down, we probably want to log it).
___
*[statstash.go, line 138 at r1](https://reviewable.io/reviews/pendo-io/statstash/9#-M10zSXPElGKA91q1OHu:-M10zSXPElGKA91q1OHv:bnr9ewp) ([raw file](https://github.com/pendo-io/statstash/blob/35f21f06a48e65ceec04b0825c49998f0fcfc149/statstash.go#L138)):*
> ```Go
> 	if _, err = s.cache.IncrementExisting(bucketKey, delta); err != nil {
> 		s.log.Warningf("Failed to increment %s delta %d", bucketKey, delta)
> 		data, _ := s.gobMarshal([]float64{float64(delta)})
> ```

Since this is a counter, you don't need all this GOB stuff, as counters are just `uint` values. Just store `uint(delta)`.

**Review by jshore1296 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/statstash/9)* status: all files reviewed, 2 unresolved discussions (waiting on @sgp)

___
*[statstash.go, line 137 at r1](https://reviewable.io/reviews/pendo-io/statstash/9#-M10y_NuANBdoDPxqNbc:-M112FClBYYoPvc5uFU7:b-896fix) ([raw file](https://github.com/pendo-io/statstash/blob/35f21f06a48e65ceec04b0825c49998f0fcfc149/statstash.go#L137)):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

This can't be a warning level log now as it's now _expected_ behavior whenever making a new key every bucket period. If you can disambiguate a cache miss error from a "bad" error", you might want to do so (because if memstore is down, we probably want to log it).
</blockquote></details>

Done.
___
*[statstash.go, line 138 at r1](https://reviewable.io/reviews/pendo-io/statstash/9#-M10zSXPElGKA91q1OHu:-M112Fah77V4iE3HGUpn:b-896fix) ([raw file](https://github.com/pendo-io/statstash/blob/35f21f06a48e65ceec04b0825c49998f0fcfc149/statstash.go#L138)):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

Since this is a counter, you don't need all this GOB stuff, as counters are just `uint` values. Just store `uint(delta)`.
</blockquote></details>

Done.

**Review by sgp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/statstash/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jshore1296 and @sgp)

___
*[statstash.go, line 137 at r1](https://reviewable.io/reviews/pendo-io/statstash/9#-M10y_NuANBdoDPxqNbc:-M116DQmCEyAcMKs42M4:brquqne) ([raw file](https://github.com/pendo-io/statstash/blob/35f21f06a48e65ceec04b0825c49998f0fcfc149/statstash.go#L137)):*
<details><summary><i>Previously, jshore1296 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd use `strconv.FormatInt(delta, 64)` in lieu of `fmt.Sprintf`.

**Review by sgp — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/statstash/9)* status: all files reviewed, 1 unresolved discussion (waiting on @jshore1296)

**Review by sgp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/statstash/9)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sgp)

___
*[statstash.go, line 137 at r1](https://reviewable.io/reviews/pendo-io/statstash/9#-M10y_NuANBdoDPxqNbc:-M118B8Z9J31_emHCym8:bnot4sf) ([raw file](https://github.com/pendo-io/statstash/blob/35f21f06a48e65ceec04b0825c49998f0fcfc149/statstash.go#L137)):*
<details><summary><i>Previously, sgp (Scott Parkerson) wrote…</i></summary><blockquote>

I'd use `strconv.FormatInt(delta, 64)` in lieu of `fmt.Sprintf`.
</blockquote></details>

Oh, derp. BASE 10, not 64 bits wide.

Das ist gut.

**Review by sgp — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/statstash/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sgp — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pendo-io/statstash/9#-:-M118QQx9X-KvYqpGu7R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
